---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: data/galleries.json
  label: Galleries
- type: document
  path: data/photos.json
  label: Photos
- type: document
  path: data/subgalleries.json
  label: Subgalleries
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*.md"
  templates:
  - project
- type: document
  path: data/species.json
  label: Species
- type: directory
  path: journal
  label: Journal
  create: documents
  match: "**/*.md"
  templates:
  - journal
- type: document
  path: data/theme.json
  label: Theme config
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gridsome build
  publish_command: gridsome build
  preview_output_directory: dist
  output_directory: dist
